### user sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json
{
    "name": "Adarsh",
    "company": "Company name",
    "address": "Some address",
    "phone": "654789310",
    "email": "e@me.com",
    "password": "secret@123"
}

### user sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "e@me.com",
    "password": "secret@123"
}


### Get a user profile endpoint
GET http://localhost:3001/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiZUBtZS5jb20iLCJpYXQiOjE3MDAyMDI4NTksImV4cCI6MTcwMDIwMzc1OX0.uVIqFkvkVPs-W3rKWYnnKT3AnpkGJrmJvRrt6dXEoXo

